### ISSUE TITLE
`Data.Map` memory leaks after an inline

### ISSUE THREAD

**Issue by nikivazou** [haskell/containers#1074]
Hey, my program returns within seconds with the below function, but runs forever when the first occurrence of `f1'` is replaced with the equivalent `f1 m`.

```
import qualified Data.Map as M

combine :: (Ord k) => (M.Map k v -> [(k, v)]) -> (M.Map k v -> [(k, v)])
        -> (M.Map k v -> [(k, v)])
combine f1 f2 m =
  let f1' = f1 m
      f2' = f2 (m `M.union` M.fromList f1') -- program does not terminate when f1' is replace with f1 m 
  in f1' ++ f2'
  ```

Not sure if this expected or known, but I cannot explain it, so reporting it in case it's worth further investigation. 

I am using `containers-0.7` and `ghc-9.10.1`.

(@pacastega)

**Comment by meooow25** [comment]
Hi, that is certainly strange, but it's hard to figure something out without knowing the inputs to the function. Do you have a reproducible example?

**Comment by nikivazou** [comment]
Let's see if we can reproduce this behavior in a small file. 
If not, if you are interested, we could give you access to the complete project that has this behavior.

**Comment by nikivazou** [comment]
[plonk-constraints-simple.zip](https://github.com/user-attachments/files/17992244/plonk-constraints-simple.zip)

Hey, I attach the project (could be even simpler, but maybe you can easily detect the error). 

in `src/GlobalStore.hs` line 38, you can change `f1'`  to `f1 m` to make it diverge.

**Comment by meooow25** [comment]
Thanks for sharing that, I think I understand what's happening.

The operational difference in replacing `f1'` with `f1 m` is that `f1` will be executed twice[^1]. This is not necessarily a problem, because if something runs twice it will just take twice as long.

But consider a structure such as

```hs
foo :: GlobalStore p b

-- left-associated sequencing
fooMany :: GlobalStore p b
fooMany = ((( ... (foo >> foo) ... >> foo) >> foo) >> foo)
```

In the result, the rightmost `>>` creates a composition where the left function is called twice.
This function is a composition from the second-rightmost `>>` which again calls the left function twice.
This function is a composition from the third-rightmost function... and so on.
This makes the running time exponential in the number of `foo`s sequenced.

Structure like this is just what we have in the `compress` function in `SHA256.hs`.

```hs
compress = aux 64 where
  ...
  aux 0 acc []     = acc
  aux l acc (p:ps) = aux (l-1) (go (64-l) acc p) ps
  ...
  go i currentHash w = do
    l <- currentHash
    ...
    return ...
```

(There may be other such places too, I haven't checked thoroughly)

So, as far as I can see

* It is not a space leak, it is just an implemention that takes exponential time.
* It is not a behavior specific to `Map`, it could happen with anything really.

```hs
-- A small reproducer using Int instead
type F = Int -> [Int]

combine' :: F -> F -> F
combine' f1 f2 m =
  let f1' = f1 m
      f2' = f2 (m + length {- f1' -} (f1 m))
  in f1' ++ f2'

foo :: F
foo !x = []

loop :: Int -> F -> F
loop 0 acc = acc
loop i acc = loop (i-1) (combine' acc foo)

main :: IO ()
main = let n = 30 in print (loop n foo 0) -- O(2^n)
```

[^1]: If GHC does not perform [CSE](https://downloads.haskell.org/ghc/latest/docs/users_guide/using-optimisation.html#ghc-flag--fcse). It does not in this case, which can be seen on checking the GHC Core.

**Comment by tomjaguarpaw** [comment]
Thanks @meooow25, very enlightening! In fact, here's an even simpler example, derived from yours, that doesn't involve lists:

```.hs
combine :: (Int -> Int) -> (Int -> Int)
combine f1 m =
  let x = f1 m
      y = f1 m
  -- If replaced by x + x there is no
  -- exponential behaviour
  in x + y 

loop :: Int -> (Int -> Int) -> (Int -> Int)
loop 0 acc = acc
loop i acc = loop (i - 1) (combine acc)

main :: IO ()
main = let n = 25 in print (loop n id 0)
```

**Comment by meooow25** [comment]
> Impressive, hopefully, it can be bypassed by the `CSE`!

GHC is conservative in applying CSE, because it does not always improve efficiency (though I wouldn't be able to tell you exactly when it applies). So it is best to not rely on it and introduce a let binding manually where you want it.

> Seems that SPJ was correct in [haskell/core-libraries-committee#310 (comment)](https://github.com/haskell/core-libraries-committee/issues/310#issuecomment-2507492841)

That is quite close to the mark :smile: 

> In fact, here's an even simpler example, derived from yours, that doesn't involve lists:

CSE kicks in in this example ([playground link](https://play.haskell.org/saved/NQ2ls307)). But yes, the slowdown can be seen if one turns off CSE or optimizations altogether.

**Comment by tomjaguarpaw** [comment]
> CSE kicks in in this example ([playground link](https://play.haskell.org/saved/NQ2ls307)). But yes, the slowdown can be seen if one turns off CSE or optimizations altogether.

Yes, you have to use `-fno-cse` or run it in `ghci`.
