### ISSUE TITLE
Consider adding `take`, `drop`, and `splitAt` to `Data.Map` and `Data.Set`

### ISSUE THREAD

**Issue by SimonMeierIBM** [haskell/containers#135]
These functions would fit nicely into the group of `Indexed` functions. One use-case for these functions is implementing a paginated view onto a large map. Currently can use a combination of `lookupIndex` and `split` to implement these functions with the right asymptotic complexity. However, it would be nice if these obvious functions would be provided in the default API.

**Comment by Gabriel439** [comment]
If the maintainers are open to this feature I would be willing to contribute the code for this

**Comment by foxik** [comment]
We usually do not add methods only because "we can", the API of containers is large as it is. Nevertheless, if there are people wanting these, we will add them.

If you are interested in this, please start discussion at libraries@haskell.org as described in the guidelines for proposers: https://wiki.haskell.org/Library_submissions#Guide_to_proposers and we will see how others feel about this.

**Comment by Gabriel439** [comment]
Alright, I'll submit a proposal to the libraries mailing list

**Comment by sjakobi** [comment]
These functions have been added in v0.5.8.1.

**Comment by treeowl** [comment]
Added in  251084a. Thanks, @sjakobi!

**Comment by treeowl** [comment]
And a few commits later to `Data.Set`.

**Comment by Gabriel439** [comment]
Thank you! :)
