### ISSUE TITLE
Improve the running time of IntSet findMin and findMax

### ISSUE THREAD

**Issue by kenta2** [haskell/containers#153]
It would be nice if the running time of findMin and findMax in IntSet were O(1) instead of the larger O(min(n,W)) as it is now.  This could be accomplished by augmenting the data structure with the min and the max elements and tracking changes with operations that modify.

**Comment by foxik** [comment]
My guess is that this is probably not going to happen -- the updating time and space costs will be probably too high for improving logarithmic complexity into constant.

Also, it is simple for `containers` users to create augmented structure which remembers the results of last `findMin` and `findMax` calls (and invalidate these when the structure is changed, without updating them immediately). That way the first `find{Min,Max}` after structure modification takes logarithmic time (for `Set` and `Map`; or the one you mentioned for `IntSet` and `IntMap`), but further calls take only constant time. Therefore, because update operations have at least that complexity, the *amortized* cost of the `find{Min,Max}` operation in the augmented structure is constant.
