### ISSUE TITLE
mergeWithKey passes empty maps to only2/only1

### ISSUE THREAD

**Issue by PapaNappa** [haskell/containers#154]
The documentation says

> When calling `mergeWithKey combine only1 only2`, a function combining two IntMaps is created, such that
> - if a key is present in both maps, it is passed with both corresponding values to the `combine` function. Depending on the result, the key is either present in the result with specified value, or is left out;
> - a nonempty subtree present only in the first map is passed to `only1` and the output is added to the result;
> - a nonempty subtree present only in the second map is passed to `only2` and the output is added to the result.

However, the following session in GHCi exhibits behaviour contrasting the documentation.

```
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
Prelude> :m Data.Map.Lazy

Prelude Data.Map.Lazy> :i empty
empty :: Map k a    -- Defined in ‘containers-0.5.6.3:Data.Map.Base’

Prelude Data.Map.Lazy> mergeWithKey (\k x1 x2 -> Just x1) (\m -> error $ "1:" ++ show m) (\m -> error $ "2:" ++ show m) empty empty
fromList *** Exception: 2:fromList []
```

I would expect that none of the functions get called.
However, although both maps are identical, `only2` is called.
Even more, the submap is empty, contradicting the statement "a _nonempty_ subtree [...] is passed to `only2`".

Further testing (now using `Debug.Trace.trace`) results in more strange behaviour:

```
Prelude Data.Map.Lazy> let m n = fromList $ zip [0..n] [0..]
Prelude Data.Map.Lazy> let onlyFun i submap = Debug.Trace.trace (show i ++ ":" ++ show submap) submap

Prelude Data.Map.Lazy> mergeWithKey (\k x1 x2 -> Just x1) (onlyFun 1) (onlyFun 2) (m 3) (m 2)
fromList 1:fromList []
1:fromList []
1:fromList []
1:fromList [(3,3)]
[(0,0),(1,1),(2,2),(3,3)]
```

I would expect that the map `fromList [(3,3)]` gets passed exactly once to `only1`.
However, it is actually called three times before, always with an empty map.

Is this the intended behaviour?
Of course, a quick work-around would be to check `Map.null submap` in the `only` functions itself.
But that's not required according to the documentation.

**Comment by foxik** [comment]
You are right, `mergeWithKey` does sometimes call `only1` or `only2` with empty subtrees. The same is the case for `IntMap.mergeWithKey`. The reason is that sometimes when we know there are no elements in the current range on one side, we pass the whole other side to the corresponding `only?` function, and do not check whether it is empty or not.

Currently I am not sure whether fixing `mergeWithKey` to perform the checks and do not pass non-empty subtree won't be too expensive (mostly for `IntMap`), so maybe I will just update the documentation. But I will benchmark it before making a decision.

So yes, `Map.null` is currently required, despite the documentation.

**Comment by meooow25** [comment]
This came up again in #979 and was fixed.
