### ISSUE TITLE
Consider adding a `range` function for Sets and Maps

### ISSUE THREAD

**Issue by w9** [haskell/containers#167]
Maybe it's my ignorance, but currently I don't know if there's an succinct way to extract a range of elements from a set (in _O(Log n)_ time). I know I can use `split` to achieve the effect:

``` haskell
import qualified Data.Set as S

-- The lower bound is inclusive and the upper bound is exclusive.
range' :: Ord a => (a, a) -> S.Set a -> S.Set a
range' (lower, upper) s = 
    let (_, e, right) = S.splitMember lower s
        (left, _)     = S.split upper right
    in  if e
          then S.union (S.singleton lower) left
          else left

main :: IO ()
main = do
    print $ range' (0, 3) (S.fromList [-1,2,0,1,5,6,3,7])
    return ()

-- output:
--   fromList [0,1,2]
```

But since this is a very common operation, can you add this function to the library? (For both `Set` and `Map`)

**Comment by foxik** [comment]
Hi,

I think using `split` is the only way to achieve what you want in logarithmic time.

As for adding a `range` function, containers API changes are usually discussed at the libraries@haskell.org mailing list. The reason is that containers API is already quite wide (and people frequently suggest functions to add), so we are careful about adding functions, and often choose not to add a function which can be easily composed. Nevertheless, I think `range` has a reasonable chance of being added.

If you are interested in this, please follow https://wiki.haskell.org/Library_submissions#Guide_to_proposers and start the discussion at libraries@haskell.org.

Cheers,
Milan

**Comment by sjakobi** [comment]
Since there hasn't been any activity here for such a long time, and since the desired function seems fairly easy to implement with [`spanAntitone`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Set.html#v:spanAntitone), I'll tentatively close this.

Please do reopen this issue if there's more to do here!

**Comment by sjakobi** [comment]
> the desired function seems fairly easy to implement with [`spanAntitone`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Set.html#v:spanAntitone),

Actually `takeWhileAntitone` and `dropWhileAntitone` might be more relevant.
