### ISSUE TITLE
highestBitMask looks crufty

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#214]
`Data.Utils.BitUtil` has

```haskell
-- | Return a word where only the highest bit is set.
highestBitMask :: Word -> Word
highestBitMask x1 = let x2 = x1 .|. x1 `shiftRL` 1
                        x3 = x2 .|. x2 `shiftRL` 2
                        x4 = x3 .|. x3 `shiftRL` 4
                        x5 = x4 .|. x4 `shiftRL` 8
                        x6 = x5 .|. x5 `shiftRL` 16
#if !(defined(__GLASGOW_HASKELL__) && WORD_SIZE_IN_BITS==32)
                        x7 = x6 .|. x6 `shiftRL` 32
                     in x7 `xor` (x7 `shiftRL` 1)
#else
                     in x6 `xor` (x6 `shiftRL` 1)
#endif
```

Could we implement this using `countLeadingZeros` and a single shift, or would that end up being slower for some reason?

**Comment by wrengr** [comment]
I think we'd need to run benchmarks on a variety of different hardware to see which is faster. I know the code used to have a rather large comment about a few different ways of implementing `highestBitMask` with some cycle-count costs for various architectures. Looks like that comment got removed somewhere along the line (though it's prolly out of date by now anyways).

In any case, predicting the cost of this function is a bit tricky since it's architecture dependent; hence wanting to run the microbenchmark on a wide variety of hardware before messing with it. I know on some architectures at least using `countLeadingZeros` followed by a shift with the second argument a variable/register instead of a literal can be quite slow.

**Comment by treeowl** [comment]
Gotcha. I'm far from a bit guru myself, which is why I could use some more
eyes on #215.

**Comment by Rufflewind** [comment]
It could be implemented as:

    highestBitMask 0 = 0
    highestBitMask x = 1 `shiftLL` (finiteBitSize x - 1 - countLeadingZeros x)

Not quite a single operation, and requires 2 branching operations (one of which is hidden inside the prim-op for `countLeadingZeros` and is also redundant here).

(If the code never uses `highestBitMask 0` then both branching operations could be removed.)

**Comment by treeowl** [comment]
Huh. I just realized the CPP there doesn't deal with non-GHC versions cleanly. It should use `finiteBitSize` to figure out whether to apply the last step in that case. As it is, I think this code will only work on 32-bit non-GHC implementations because the non-GHC definition of `shiftRL` uses `shiftR` instead of the more recent `unsafeShiftR`. Fragile.

**Comment by treeowl** [comment]
Hmph. I guess improving on this is harder than it looks.
