### ISSUE TITLE
Add Data.Sequence.unzip

### ISSUE THREAD

**Issue by Blaisorblade** [haskell/containers#320]
Current proposal I just needed in my code (typechecks, makes sense, untested, laziness not reviewed):

``` haskell
import           Data.Sequence (Seq, (><), (<|))
import qualified Data.Sequence as S

-- Based on Prelude.unzip
unzip :: Seq (a, b) -> (Seq a, Seq b)
unzip = foldr (\(a, b) ~(as, bs) -> (a <| as, b <| bs)) (S.empty, S.empty)
```

Searching this repo found no relevant mention of `unzip`.

**Comment by treeowl** [comment]
I agree with this idea, but the implementation is not good. I would want something more like this (untested and not even type checked):

```haskell
unzipWith :: (a -> (b,c)) -> Seq a -> (Seq b, Seq c)
unzipWith f (Seq xs) = bimap Seq Seq $! unzipTree (\(Elem x) -> bimap Elem Elem $! f x) xs

unzipTree :: (a -> (b,c)) -> FingerTree a -> (FingerTree b, FingerTree c)
unzipTree _ EmptyT = (EmptyT, EmptyT)
unzipTree f (Single xs) = bimap Single Single $! f xs
unzipTree f (Deep s pr m sf) =
  let
    !(pr1, pr2) = unzipDigit f pr
    !(sf1, sf2) = unzipDigit f sf
    (m1, m2) = unzipTree (unzipNode f) m
  in (Deep s pr1 m1 sf1, Deep s pr2 m2 sf2)

unzipNode :: (a -> (b, c)) -> Node a -> (Node b, Node c)
unzipNode f (Node2 s x y) =
  let
    (x1, x2) = f x
    (y1, y2) = f y
  in (Node2 s x1 y1, Node2 s x2 y2)
unzipNode f (Node3 s x y z) = ...
```

**Comment by treeowl** [comment]
Note that for GHC 7.8 and above, `unzipWith` is basically `coerce unzipTree`, but it'll probably take a bit of fussing to get the types right.

**Comment by Blaisorblade** [comment]
> I agree with this idea, but the implementation is not good

Makes sense, that's the quickest thing that made any sense. If a proper implementation isn't trivial, it's more important that `containers` include it.

I agree one should work on the underlying representation instead of using `foldr`, if there isn't a better combinator for getting that effect—at least the API doesn't include such a combinator (I'd hope for a fold on the actual implementation).

Given that Prelude's unzip takes care to use an irrefutable pattern match and your implementation uses `$!`, I'm wondering on the correct strictness—but quite possibly infinite finger trees don't make sense.

**Comment by Blaisorblade** [comment]
Separately, I also needed this combinator:

```
import Data.Sequence
import qualified Data.Sequence as S

subseq :: Seq a -> Int -> Int -> Seq a
subseq xs src len = S.take len $ S.drop src xs
```

Looking at your code and what I know on fingertrees, I imagine that could maybe also be optimized? (I can open a separate issue if appropriate).

**Comment by treeowl** [comment]
Length-annotated finger trees don't support infinite sequences, so that's
not an issue. For efficiency, it tends

**Comment by treeowl** [comment]
Length-annotated finger trees don't support infinite sequences, so that's
not an issue. For efficiency, map-like operations should generally be lazy
in the nodes and digits and down the spine (middles). Gratuitously
producing lazy pairs elsewhere has little to recommend it. Note that the
list version is also somewhat strict in the pairs, and also the list
structure:

unzip [(1,2), undefined, (3,4)] = (1 : undefined, 2 : undefined)

A maximally lazy version would give

([1, undefined, 3], [2, undefined, 4])

unzip undefined = undefined

A *really* gratuitously lazy version would give (undefined, undefined)

You could reasonably argue that Data.Sequence should be lazier in the
sequence elements, so as to have a more predictable/understandable
strictness "story", but you'd have to demonstrate that performance wasn't
too negatively affected.

**Comment by treeowl** [comment]
With the new take and drop code in git master, I expect your subseq will
likely be pretty fast, although you should be able to speed it up by being
sure to split it first at whichever point is closer to an end of the
sequence. Suppose your split points are m < n

0     m    n      (length xs)

If m is closer to 0 than n is to length xs, then you should first drop m,
then take n-m. If it's the other way around, you should first take n, then
drop m.

I don't know how to improve on it under the hood off the top of my head. I
suspect it's possible, but the code would be rather involved.

**Comment by Blaisorblade** [comment]
Thanks for all your explanations! 😍 
I guess I should leave this to you. I could try a PR if you want, but I guess you'd be faster on your own.

> You could reasonably argue that Data.Sequence should be lazier in the sequence elements

Being consistent with current practice is fine with me, and docs even mention this difference:

> Apart from being finite and having strict operations, sequences also differ from lists in supporting a wider variety of operations efficiently.

**Comment by treeowl** [comment]
The weird bit is that the way I want to write it,

unzip [(x,y), undefined, ...]

will likely come out undefined, but

unzip [... At least four elements... undefined ... At least four elements]

will not. That's weird enough I might just go for super-lazy so I have
semantics I can document.

**Comment by Blaisorblade** [comment]
Since the docs say "strict" once, it *might* be easier to document a stricter version—could it be written? Otherwise your idea makes sense.

**Comment by treeowl** [comment]
The additional strictness is generally in notional structure rather than
elements. In particular, a sequence is strict in its *length*. I'll have to
think more about how I want unzipping to go, and probably consult some
other folks.

**Comment by Blaisorblade** [comment]
> The additional strictness is generally in notional structure rather than
> elements.

Ah I kind-of see (that means spine-strict I suspect).
That *might* warrant some extra explanation on the docs then.

> probably consult some other folks.

Probably good, thanks for putting up with me.

**Comment by treeowl** [comment]
It's a bit more complicated than that. To understand it properly, you
should separate the oppositions eager/lazy from strict/non-strict.
Sequences represent structurally strict finite sequences (operationally,
they are strict in their size annotations), but are implemented using a lot
of laziness. Laziness in the spine is necessary for amortized O(1) deque
operations, and laziness throughout the structure is important for vaguely
map-like operations. You should probably skim the finger tree paper by
Hinze and Paterson. It's quite readable, and explains a fair bit.

On Aug 16, 2016 5:17 PM, "Paolo G. Giarrusso" <notifications@github.com>
wrote:

The additional strictness is generally in notional structure rather than
elements.

Ah I kind-of see (that means spine-strict I suspect).
That *might* warrant some extra explanation on the docs then.

probably consult some other folks.

Probably good, thanks for putting up with me.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/320#issuecomment-240241873>,
or mute the thread

**Comment by sjakobi** [comment]
[`unzip`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Sequence.html#v:unzip) and [`unzipWith`](http://hackage.haskell.org/package/containers-0.6.3.1/docs/Data-Sequence.html#v:unzipWith) were added in 0.5.11.

Please reopen if there's more to do here.
