### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by giovannirescia** [haskell/containers#347]
Hi there!

I am working in a code that's not mine, so I can't understand it very well and therefore explain what I am doing (or trying to do). But the error that I get is the next:

`"index out of bounds\nCallStack (from HasCallStack):\n  error, called at ./Data/Sequence/Base.hs:1791:
19 in containers-0.5.8.1-GB7XRscggFnIkqZLCK9AcT:Data.Sequence.Base"`

I do not know a lot of Haskell also, so I can't interpret that message. Does anybody can help me to fix it or understand it?

Thanks a lot!
Giovanni

**Comment by treeowl** [comment]
This is not nearly enough information to diagnose any problem. It sounds like the code you're using is probably calling `Data.Sequence.index` with a negative index or one too large for the sequence being indexed. I'll leave this ticket open briefly, because there is a sort of bug--the error message should mention the `index` function. But for help debugging your project, you should probably head to the `#haskell` channel on FreeNode, the haskell-beginners mailing list on haskell.org, or StackOverflow.

**Comment by giovannirescia** [comment]
Ok, thank you very much!

**Comment by m-renaud** [comment]
Error message improved in #457 so I'm going to close this issue.
