### ISSUE TITLE
Data.IntMap.restrictKeys and Data.IntMap.withoutKeys not working

### ISSUE THREAD

**Issue by tomsmalley** [haskell/containers#392]
I'm using containers-0.5.9.1, this is observable on both strict and lazy versions of IntMap:

```haskell
λ GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
λ import qualified Data.IntMap as M
λ import qualified Data.IntSet as S
λ let m = M.fromList [(1,'a'), (3,'b')]
λ M.restrictKeys m (S.singleton 1)
fromList []
λ M.withoutKeys m (S.singleton 1)
fromList [(1,'a'),(3,'b')]
```

Using the example definitions from the documentation works:

```haskell
λ let restrictKeys m s = M.filterWithKey (\k _ -> k `S.member` s) m
λ let withoutKeys m s = M.filterWithKey (\k _ -> k `S.notMember` s) m
λ restrictKeys m (S.singleton 1)
fromList [(1,'a')]
λ withoutKeys m (S.singleton 1)
fromList [(3,'b')]
```

**Comment by treeowl** [comment]
Oh great. This looks bad. I'll look into it today.

On Feb 6, 2017 10:30 AM, "Tom Smalley" <notifications@github.com> wrote:

I'm using containers-0.5.9.1

λ GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
λ import qualified Data.IntMap as M
λ import qualified Data.IntSet as S
λ let m = M.fromList [(1,'a'), (3,'b')]
λ M.restrictKeys m (S.singleton 1)
fromList []
λ M.withoutKeys m (S.singleton 1)
fromList [(1,'a'),(3,'b')]

Using the example definitions from the documentation works:

λ let restrictKeys m s = M.filterWithKey (\k _ -> k `S.member` s) m
λ let withoutKeys m s = M.filterWithKey (\k _ -> k `S.notMember` s) m
λ restrictKeys m (S.singleton 1)
fromList [(1,'a')]
λ withoutKeys m (S.singleton 1)
fromList [(3,'b')]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/392>, or mute the thread

**Comment by treeowl** [comment]
Crud. I totally goofed those implementations, and then I messed up when
adding the functions to the test suite so I didn't notice. Argh! This will
be a scramble.

On Feb 6, 2017 2:36 PM, "David Feuer" <david.feuer@gmail.com> wrote:

Oh great. This looks bad. I'll look into it today.


On Feb 6, 2017 10:30 AM, "Tom Smalley" <notifications@github.com> wrote:

I'm using containers-0.5.9.1

λ GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
λ import qualified Data.IntMap as M
λ import qualified Data.IntSet as S
λ let m = M.fromList [(1,'a'), (3,'b')]
λ M.restrictKeys m (S.singleton 1)
fromList []
λ M.withoutKeys m (S.singleton 1)
fromList [(1,'a'),(3,'b')]

Using the example definitions from the documentation works:

λ let restrictKeys m s = M.filterWithKey (\k _ -> k `S.member` s) m
λ let withoutKeys m s = M.filterWithKey (\k _ -> k `S.notMember` s) m
λ restrictKeys m (S.singleton 1)
fromList [(1,'a')]
λ withoutKeys m (S.singleton 1)
fromList [(3,'b')]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/392>, or mute the thread

**Comment by treeowl** [comment]
@tomsmalley, I think I've fixed this, and I intend to make a release this evening. Do you think you have the time to test out the fix against some larger examples, preferably with keys in a wide variety of ranges and signs? If not, I'll give it a go.

**Comment by tomsmalley** [comment]
Fantastic, very fast fix!
I'll have a look tomorrow, I'm working with a dataset of a few million in size (positive keys only though).
Many thanks.

**Comment by tomsmalley** [comment]
@treeowl, looks to be working well!

**Comment by treeowl** [comment]
Excellent! Glad I didn't mess that one up again!
