### ISSUE TITLE
benchmarking the "append" operation

### ISSUE THREAD

**Issue by jwaldmann** [haskell/containers#419]
Hi. Do you have any thoughts on https://github.com/haskell-perf/sequences/issues/7 (how to measure the cost of append in Data.Sequence)?

**Comment by chrisdone** [comment]
For context, we've noticed that doing an `(<>)` on two sequences yields _O(n)_-ish time, worse than a list:

https://github.com/haskell-perf/sequences#append

It should be _O(log n)_ (both arguments to `><` are the same size).

We're using `nf`, to be sure that laziness isn't avoiding work that would be done later anyway.

But we're unsure about whether that forces the structure twice, so that your benchmark numbers will always be yielding `O(n)` times as the input scales.

I see in your own benchmark suite that it does an `nf`: https://github.com/haskell/containers/blob/master/benchmarks/Sequence.hs#L32

Any thoughts?

**Comment by chrisdone** [comment]
With a `whnf . length` it seems to produce fairer results. 

https://github.com/haskell-perf/sequences#append

Gives us a constant factor for Seq's append... which is probably incorrect?

**Comment by chrisdone** [comment]
It might be worth taking it a bit further by establishing some baselines between the data structures. I think I'll try benchmarking how fast a deepseq is, and then subtract that time from the end results. I'll try that after lunch.

**Comment by chrisdone** [comment]
I think we have  good result with a weak head force and the latest containers: https://github.com/haskell-perf/sequences/issues/7#issuecomment-286140486

**Comment by treeowl** [comment]
It seems like this was a measurement-related issue, rather than really an implementation one.

**Comment by chrisdone** [comment]
Yep, thanks @treeowl!
