### ISSUE TITLE
Cut a release for GHC 8.4

### ISSUE THREAD

**Issue by bgamari** [haskell/containers#501]
The GHC 8.4.1 release is quickly approaching and i would like to have all of the submodules finalized by next alpha. For this we'll need a new release.

**Comment by treeowl** [comment]
I should be able to do that today or tomorrow. Thanks for the heads up.

On Jan 21, 2018 3:29 PM, "Ben Gamari" <notifications@github.com> wrote:

The GHC 8.4.1 release is quickly approaching and i would like to have all
of the submodules finalized by next alpha. For this we'll need to cut a new
release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/containers/issues/501>, or mute the thread

**Comment by sjakobi** [comment]
I guess this can be closed.
