### ISSUE TITLE
Pattern synonym for singleton sets and expose `Tip`

### ISSUE THREAD

**Issue by fakedrake** [haskell/containers#574]
Ideally  something like:

```
pattern SingletonSet x = Bin 1 x Tip Tip
```

That would be nice

**Comment by treeowl** [comment]
What makes that a useful pattern? Please offer applications!

**Comment by safinaskar** [comment]
@treeowl , what if I want to check that the set is singleton and if it actually is, extract its element and do something with it?

Idiomatic way to do this with lists is this:
```haskell
case someList of {
  [x] -> {- do something with x -}
  _ -> {- do something else -}
}
```
We need something like this for sets and other containers.
Moreover, patterns are good when they are exhaustive. So, instead of singleton pattern offered by @fakedrake I will offer two different patterns: one for empty set and one "minimal element and everything else". You will use them so:
```haskell
case someSet of {
  Set.Empty -> ...;
  Set.Min x y -> {- here x is minimal element of someSet and
  y is set of everything else -}
}
-- Compiler will check that this two patterns are actually exhaustive
-- and that we will not catch a runtime error. Cool!
```
Singleton pattern becomes not-needed, because we can write it simply as `Set.Min x Set.Empty`.

I think that every time when you have some way to create instance of your datatype, and it can be written as pattern, and actual data constructors are implementation detail, then you should define patterns. Especially if some of this ways combine into exhaustive groups. Check Haskell blogs, I am sure they wrote more arguments about this.

So, I propose adding to Set exhaustive combination of two patterns: Empty and Min. And also another exhaustive combination: Empty and Max. The same should be done for Map and possibly other containers.

Also, here is actual use case I got right now, when writing my real world program. I wanted to check whether my map of type `Map.Map Alternative (Map.Map (Maybe Field) ValueType)` is singleton map with key Unique (this is type constructor for my data type Alternative) of empty map. And if it is then I wanted to do nothing (in monad), i. e. perform `return ()`. And if it is not, I wanted to `throwError ...`. So I wrote:

```haskell
when (fields /= Map.singleton Unique Map.empty) $ throwError "..."
```

But this is bad, because this requires `Map.Map (Maybe Field) ValueType` to be `Eq`. In my program it is actually `Eq`, but in general in some other program it is possible it would not be `Eq`. Also, it seems my code actually invokes `==` on internal map (i. e. on map of type `Map.Map (Maybe Field) ValueType`) and this can have performance implications.

If you implemented this patterns, I would write something like this:
```haskell
case fields of {
  Map.Min Unique Map.Empty Map.Empty -> return ();
  _ -> throwError "...";
}
```
Now we don't need internal map to be `Eq`

**Comment by sjakobi** [comment]
This issue seems so closely related to #552 that I'd suggest closing this as a duplicate.

**Comment by treeowl** [comment]
Agreed.
