### ISSUE TITLE
Consider adding implementations of Foldable's new foldMap' method

### ISSUE THREAD

**Issue by sjakobi** [haskell/containers#578]
In base-4.13 `Foldable` gains a new method `foldMap'`, a strict version of `foldMap`. There might be a benefit in having custom implementations of that method here.

**Comment by sjakobi** [comment]
> For `Data.Sequence`, the one to ask is @oisdk. I'll have a look at `Data.Map` and `Data.Set`.



Any news on this @oisdk, @treeowl?

In particular I could use `Data.Map.foldMapWithKey'` right now…

**Comment by sjakobi** [comment]
> In particular I could use `Data.Map.foldMapWithKey'` right now…

Actually I could make do with `foldlWithKey'`. :)

**Comment by sjakobi** [comment]
I took a cursory look at the various `Foldable` instances and got the impression that the default definitions via `foldl'` should be fine. The one exception was `Tree` which doesn't have a custom `foldl'`.

I wouldn't mind if this issue was closed. What do you think @treeowl?

**Comment by meooow25** [comment]
`foldMap'`'s [default definition](https://hackage.haskell.org/package/base-4.19.0.0/docs/src/Data.Foldable.html#foldMap%27) is

```hs
    foldMap' :: Monoid m => (a -> m) -> t a -> m
    foldMap' f = foldl' (\ acc a -> acc <> f a) mempty
```

which should work fine for all structures in `containers`. I can't think of any case where a different implementation would be better.

Perhaps the default definition should have an `INLINE`, but that is a `base` problem.


> The one exception was `Tree` which doesn't have a custom `foldl'`.

`Foldable Tree` defines `foldl'` since #880.
