### ISSUE TITLE
Set has the "wrong" type for GHC

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#60]
Reasonably recent GHC versions support GADTs, which allow class constraints on constructors. This suggests something like the following type for `Set`:

```
data Set a where
   Bin :: Ord a => {-# UNPACK #-} !Size -> !a -> !(Set a) -> !(Set a) -> Set a
   Tip :: Set a
```

I would _speculate_ that a little CPP could let `Set` use this definition  or something similar (and the O(log n) implementation of `Data.Foldable.elem` that goes with it) where supported with minimal internal or external breakage.

**Comment by alexfmpe** [comment]
I fell down this rabbit hole recently while wondering whether there was a difference using `elem` or `member` for `Set`. The situation makes sense once you remember `elem` does not have access to `Ord a`, but at first I was suprised to find out we have
```haskell
elem = go
  where go !_ Tip = False
    go x (Bin _ y l r) = x == y || go x l || go x r
```
in other words, that `elem` linearly scans the tree rather than do binary search. And sure enough, if we add a benchmark 
```
All
  member: OK
    1.21 ms ± 112 μs, 480 KB allocated,  42 B  copied, 107 MB peak memory
  elem:   OK
    110  ms ± 8.4 ms, 482 KB allocated, 651 B  copied, 107 MB peak memory

All 2 tests passed (3.30s)
```
we get a massive difference, that will only increase in size as a `Set` grows. Is `Set.elem` a footgun? 
Or is it desired if we treat the mental model for `Foldable` that it accumulate over all elements with only the binary function allowed to do "control flow" via short circuit under lazyness?

> Not yet ripe.

AFAICT both GHC and MHS support `GADTs`. If we're worried about other implementations, maybe we could CPP that away
```haskell
#if defined(__GLASGOW_HASKELL__) || defined(__MHS__)
type CompatOrd a = Set a
#else 
type CompatOrd a = ()
#endif 
```

> I would speculate that a little CPP could let Set use this definition or something similar (and the O(log n) implementation of Data.Foldable.elem that goes with it) where supported with minimal internal or external breakage.

The internal breakage is indeed minimal, mostly adding `Ord a` to a [couple dozen signatures](https://github.com/alexfmpe/containers/commit/e2fdf40082d40dd4df89ce63c71347eed3d75a82), which morally look like they should have them anyway given without constraints on `a`, `Set a` is a misleading `List a`?

As for external breakage, well, we hit it right away
```
$ cabal test set-properties
Build profile: -w ghc-9.10.3 -O1
In order, the following will be built (use -v for more details):
 - QuickCheck-2.17.1.0 (lib) (file /Users/alexfmpe/profiles/alexfmpe/repos/containers/dist-newstyle/build/aarch64-osx/ghc-9.10.3/containers-0.8/cache/build changed)
 - binary-0.8.9.3 (lib) (file /Users/alexfmpe/profiles/alexfmpe/repos/containers/dist-newstyle/build/aarch64-osx/ghc-9.10.3/containers-0.8/cache/build changed)
 - containers-tests-0 (lib) (file benchmarks/Set.hs changed)
 - quickcheck-classes-base-0.6.2.0 (lib) (configuration changed)
 - ChasingBottoms-1.3.1.17 (lib) (configuration changed)
 - text-2.1.4 (lib) (configuration changed)
 - prettyprinter-1.7.1 (lib) (configuration changed)
 - prettyprinter-ansi-terminal-1.1.3 (lib) (configuration changed)
 - optparse-applicative-0.19.0.0 (lib) (configuration changed)
 - tasty-1.5.4 (lib) (configuration changed)
 - tasty-quickcheck-0.11.1 (lib) (configuration changed)
 - tasty-hunit-0.10.2 (lib) (configuration changed)
 - containers-tests-0 (lib:test-utils) (configuration changed)
 - containers-tests-0 (test:set-properties) (configuration changed)
Preprocessing library for binary-0.8.9.3...
Preprocessing library for containers-tests-0...
Preprocessing library for QuickCheck-2.17.1.0...
Building library for binary-0.8.9.3...
Building library for QuickCheck-2.17.1.0...
Building library for containers-tests-0...
[7 of 9] Compiling Data.Binary.Class ( src/Data/Binary/Class.hs, /Users/alexfmpe/profiles/alexfmpe/repos/containers/dist-newstyle/build/aarch64-osx/ghc-9.10.3/binary-0.8.9.3/build/Data/Binary/Class.o, /Users/alexfmpe/profiles/alexfmpe/repos/containers/dist-newstyle/build/aarch64-osx/ghc-9.10.3/binary-0.8.9.3/build/Data/Binary/Class.dyn_o ) [Data.Map.Internal changed]
src/Data/Binary/Class.hs:656:19: error: [GHC-39999]
    • Could not deduce ‘Ord a’
        arising from a use of ‘Set.fromDistinctAscList’
      from the context: Binary a
        bound by the instance declaration
        at src/Data/Binary/Class.hs:654:10-41
      Possible fix:
        add (Ord a) to the context of the instance declaration
    • In the first argument of ‘liftM’, namely
        ‘Set.fromDistinctAscList’
      In the expression: liftM Set.fromDistinctAscList get
      In an equation for ‘get’: get = liftM Set.fromDistinctAscList get
    |
656 |     get   = liftM Set.fromDistinctAscList get
    |                   ^^^^^^^^^^^^^^^^^^^^^^^
```

Because [`Binary (Set a)`](https://hackage.haskell.org/package/binary-0.8.9.3/docs/src/Data.Binary.Class.html#line-654) does not require `Ord a` (and if it did, that'd trigger a warning). So I expect a good deal of breakage, though each occurence is probably trivial to fix except maybe for cases where the use of `Set` is utterly broken?

I'd think we could allow some forward-compat by exporting 
```haskell
type CompatOrd a = ()
```
and past a migration period change it into
```haskell
type CompatOrd a = Set a
```
and eventually retiring `CompatOrd` where `GADTs` are available. Though even in GHC 9.14,
```haskell
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE LiberalTypeSynonyms #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
instance CompatOrd a => Monoid (Set a) where 
```
gives me 
```
• Expected a constraint, but ‘CompatOrd a’ is a type
• In the instance declaration for ‘Monoid (Set a)
```
so I don't know. Maybe instead we'd roll with
```haskell
class Ord a => CompatOrd a
instance Ord a => CompatOrd a
```
