### ISSUE TITLE
Add Generic instance for Data.Sequence.Seq

### ISSUE THREAD

**Issue by ocramz** [haskell/containers#634]
I was wondering why `Seq` doesn't have a `Generic` instance, but `FingerTree`, `ViewL` and `ViewR` do.
It would be handy for many things, e.g. using sequences as keys in `HashMap`s.

**Comment by treeowl** [comment]
Because `Seq` is abstract, and `Generic` would reveal internals. In particular, `s1 == s2 = True` would not imply `from s1 == from s2 = True`. A `Generic` instance wouldn't really help you much for `HashMap`; there's no `Hashable` instance because `hashable` doesn't depend on `containers` and vice versa. You could open a PR to `hashable-orphans`, I suppose. You just need `foldl'`.

**Comment by ocramz** [comment]
What if I promised to never ever compare the generic encodings of two `Seq`s ?

**Comment by treeowl** [comment]
You can also use `to` to produce bogus sequences that violate internal size annotation invariants. What do you actually want this instance *for*?

**Comment by ocramz** [comment]
Understood, this was not a sensible feature to ask.
